// This file is auto-generated by timber.js. Do not edit.
// It ensures TypeScript picks up the generated route types and
// Vite-provided ambient types (CSS, assets, import.meta.env, HMR).
/* eslint-disable @typescript-eslint/triple-slash-reference */
/// <reference path=".timber/timber-routes.d.ts" />
/// <reference types="vite/client" />
