// This file is auto-generated by timber.js. Do not edit.
// It ensures TypeScript picks up the generated route types.
// eslint-disable-next-line @typescript-eslint/triple-slash-reference
/// <reference path=".timber/timber-routes.d.ts" />
