// This file is auto-generated by timber.js route map codegen.
// Do not edit manually. Regenerated on build and in dev mode.

export {};

declare module '@timber-js/app' {
  interface Routes {
    '/': {
      params: {}
      searchParams: {}
    }
    '/': {
      params: {}
      searchParams: {}
    }
    '/': {
      params: {}
      searchParams: {}
    }
    '/': {
      params: {}
      searchParams: {}
    }
    '/': {
      params: {}
      searchParams: {}
    }
    '/[...artistSlug]': {
      params: { artistSlug: string[] }
      searchParams: {}
    }
    '/[artistSlug]': {
      params: { artistSlug: string }
      searchParams: {}
    }
    '/[artistSlug]': {
      params: { artistSlug: string }
      searchParams: {}
    }
    '/[artistSlug]': {
      params: { artistSlug: string }
      searchParams: {}
    }
    '/[artistSlug]': {
      params: { artistSlug: string }
      searchParams: {}
    }
    '/[artistSlug]/[...year]': {
      params: { artistSlug: string; year: string[] }
      searchParams: {}
    }
    '/[artistSlug]/[year]': {
      params: { artistSlug: string; year: string }
      searchParams: {}
    }
    '/[artistSlug]/[year]': {
      params: { artistSlug: string; year: string }
      searchParams: {}
    }
    '/[artistSlug]/[year]': {
      params: { artistSlug: string; year: string }
      searchParams: {}
    }
    '/[artistSlug]/[year]/[month]': {
      params: { artistSlug: string; year: string; month: string }
      searchParams: {}
    }
    '/[artistSlug]/[year]/[month]/[...day]': {
      params: { artistSlug: string; year: string; month: string; day: string[] }
      searchParams: {}
    }
    '/[artistSlug]/[year]/[month]/[...day]': {
      params: { artistSlug: string; year: string; month: string; day: string[] }
      searchParams: {}
    }
    '/[artistSlug]/[year]/[month]/[day]': {
      params: { artistSlug: string; year: string; month: string; day: string }
      searchParams: {}
    }
    '/[artistSlug]/[year]/[month]/[day]/[songSlug]': {
      params: { artistSlug: string; year: string; month: string; day: string; songSlug: string }
      searchParams: {}
    }
    '/about': {
      params: {}
      searchParams: {}
    }
    '/album-art': {
      params: {}
      searchParams: {}
    }
    '/api/og': {
      params: {}
      searchParams: {}
    }
    '/api/status': {
      params: {}
      searchParams: {}
    }
    '/app': {
      params: {}
      searchParams: {}
    }
    '/chat': {
      params: {}
      searchParams: {}
    }
    '/embed-test': {
      params: {}
      searchParams: {}
    }
    '/embed/[artistSlug]/[year]/[month]/[day]': {
      params: { artistSlug: string; year: string; month: string; day: string }
      searchParams: {}
    }
    '/embed/[artistSlug]/[year]/[month]/[day]/[songSlug]': {
      params: { artistSlug: string; year: string; month: string; day: string; songSlug: string }
      searchParams: {}
    }
    '/recently-played': {
      params: {}
      searchParams: {}
    }
    '/sonos': {
      params: {}
      searchParams: {}
    }
    '/today': {
      params: {}
      searchParams: {}
    }
  }
}

declare module '@timber-js/app/server' {
  import type { Routes } from '@timber-js/app'
  export function searchParams<R extends keyof Routes>(): Promise<Routes[R]['searchParams']>
}

declare module '@timber-js/app/client' {
  import type { SearchParamsDefinition, SetParams, QueryStatesOptions, SearchParamCodec } from '@timber-js/app/search-params'

  export function useParams(route: '/[...artistSlug]'): { artistSlug: string[] }
  export function useParams(route: '/[artistSlug]'): { artistSlug: string }
  export function useParams(route: '/[artistSlug]'): { artistSlug: string }
  export function useParams(route: '/[artistSlug]'): { artistSlug: string }
  export function useParams(route: '/[artistSlug]'): { artistSlug: string }
  export function useParams(route: '/[artistSlug]/[...year]'): { artistSlug: string; year: string[] }
  export function useParams(route: '/[artistSlug]/[year]'): { artistSlug: string; year: string }
  export function useParams(route: '/[artistSlug]/[year]'): { artistSlug: string; year: string }
  export function useParams(route: '/[artistSlug]/[year]'): { artistSlug: string; year: string }
  export function useParams(route: '/[artistSlug]/[year]/[month]'): { artistSlug: string; year: string; month: string }
  export function useParams(route: '/[artistSlug]/[year]/[month]/[...day]'): { artistSlug: string; year: string; month: string; day: string[] }
  export function useParams(route: '/[artistSlug]/[year]/[month]/[...day]'): { artistSlug: string; year: string; month: string; day: string[] }
  export function useParams(route: '/[artistSlug]/[year]/[month]/[day]'): { artistSlug: string; year: string; month: string; day: string }
  export function useParams(route: '/[artistSlug]/[year]/[month]/[day]/[songSlug]'): { artistSlug: string; year: string; month: string; day: string; songSlug: string }
  export function useParams(route: '/embed/[artistSlug]/[year]/[month]/[day]'): { artistSlug: string; year: string; month: string; day: string }
  export function useParams(route: '/embed/[artistSlug]/[year]/[month]/[day]/[songSlug]'): { artistSlug: string; year: string; month: string; day: string; songSlug: string }
  export function useParams(): Record<string, string | string[]>

  export function useQueryStates<R extends '/'>(route: R, options?: QueryStatesOptions): [{}, SetParams<{}>]
  export function useQueryStates<R extends '/'>(route: R, options?: QueryStatesOptions): [{}, SetParams<{}>]
  export function useQueryStates<R extends '/'>(route: R, options?: QueryStatesOptions): [{}, SetParams<{}>]
  export function useQueryStates<R extends '/'>(route: R, options?: QueryStatesOptions): [{}, SetParams<{}>]
  export function useQueryStates<R extends '/'>(route: R, options?: QueryStatesOptions): [{}, SetParams<{}>]
  export function useQueryStates<R extends '/[...artistSlug]'>(route: R, options?: QueryStatesOptions): [{}, SetParams<{}>]
  export function useQueryStates<R extends '/[artistSlug]'>(route: R, options?: QueryStatesOptions): [{}, SetParams<{}>]
  export function useQueryStates<R extends '/[artistSlug]'>(route: R, options?: QueryStatesOptions): [{}, SetParams<{}>]
  export function useQueryStates<R extends '/[artistSlug]'>(route: R, options?: QueryStatesOptions): [{}, SetParams<{}>]
  export function useQueryStates<R extends '/[artistSlug]'>(route: R, options?: QueryStatesOptions): [{}, SetParams<{}>]
  export function useQueryStates<R extends '/[artistSlug]/[...year]'>(route: R, options?: QueryStatesOptions): [{}, SetParams<{}>]
  export function useQueryStates<R extends '/[artistSlug]/[year]'>(route: R, options?: QueryStatesOptions): [{}, SetParams<{}>]
  export function useQueryStates<R extends '/[artistSlug]/[year]'>(route: R, options?: QueryStatesOptions): [{}, SetParams<{}>]
  export function useQueryStates<R extends '/[artistSlug]/[year]'>(route: R, options?: QueryStatesOptions): [{}, SetParams<{}>]
  export function useQueryStates<R extends '/[artistSlug]/[year]/[month]'>(route: R, options?: QueryStatesOptions): [{}, SetParams<{}>]
  export function useQueryStates<R extends '/[artistSlug]/[year]/[month]/[...day]'>(route: R, options?: QueryStatesOptions): [{}, SetParams<{}>]
  export function useQueryStates<R extends '/[artistSlug]/[year]/[month]/[...day]'>(route: R, options?: QueryStatesOptions): [{}, SetParams<{}>]
  export function useQueryStates<R extends '/[artistSlug]/[year]/[month]/[day]'>(route: R, options?: QueryStatesOptions): [{}, SetParams<{}>]
  export function useQueryStates<R extends '/[artistSlug]/[year]/[month]/[day]/[songSlug]'>(route: R, options?: QueryStatesOptions): [{}, SetParams<{}>]
  export function useQueryStates<R extends '/about'>(route: R, options?: QueryStatesOptions): [{}, SetParams<{}>]
  export function useQueryStates<R extends '/app'>(route: R, options?: QueryStatesOptions): [{}, SetParams<{}>]
  export function useQueryStates<R extends '/chat'>(route: R, options?: QueryStatesOptions): [{}, SetParams<{}>]
  export function useQueryStates<R extends '/embed-test'>(route: R, options?: QueryStatesOptions): [{}, SetParams<{}>]
  export function useQueryStates<R extends '/embed/[artistSlug]/[year]/[month]/[day]'>(route: R, options?: QueryStatesOptions): [{}, SetParams<{}>]
  export function useQueryStates<R extends '/embed/[artistSlug]/[year]/[month]/[day]/[songSlug]'>(route: R, options?: QueryStatesOptions): [{}, SetParams<{}>]
  export function useQueryStates<R extends '/recently-played'>(route: R, options?: QueryStatesOptions): [{}, SetParams<{}>]
  export function useQueryStates<R extends '/sonos'>(route: R, options?: QueryStatesOptions): [{}, SetParams<{}>]
  export function useQueryStates<R extends '/today'>(route: R, options?: QueryStatesOptions): [{}, SetParams<{}>]
  export function useQueryStates<T extends Record<string, unknown>>(codecs: { [K in keyof T]: SearchParamCodec<T[K]> }, options?: QueryStatesOptions): [T, SetParams<T>]

  // Typed Link props per route
  export function Link(props: Omit<import('react').AnchorHTMLAttributes<HTMLAnchorElement>, 'href'> & {
    href: '/'
    params?: never
    searchParams?: never
    prefetch?: boolean; scroll?: boolean; children?: import('react').ReactNode
  }): import('react').JSX.Element
  export function Link(props: Omit<import('react').AnchorHTMLAttributes<HTMLAnchorElement>, 'href'> & {
    href: '/'
    params?: never
    searchParams?: never
    prefetch?: boolean; scroll?: boolean; children?: import('react').ReactNode
  }): import('react').JSX.Element
  export function Link(props: Omit<import('react').AnchorHTMLAttributes<HTMLAnchorElement>, 'href'> & {
    href: '/'
    params?: never
    searchParams?: never
    prefetch?: boolean; scroll?: boolean; children?: import('react').ReactNode
  }): import('react').JSX.Element
  export function Link(props: Omit<import('react').AnchorHTMLAttributes<HTMLAnchorElement>, 'href'> & {
    href: '/'
    params?: never
    searchParams?: never
    prefetch?: boolean; scroll?: boolean; children?: import('react').ReactNode
  }): import('react').JSX.Element
  export function Link(props: Omit<import('react').AnchorHTMLAttributes<HTMLAnchorElement>, 'href'> & {
    href: '/'
    params?: never
    searchParams?: never
    prefetch?: boolean; scroll?: boolean; children?: import('react').ReactNode
  }): import('react').JSX.Element
  export function Link(props: Omit<import('react').AnchorHTMLAttributes<HTMLAnchorElement>, 'href'> & {
    href: '/[...artistSlug]'
    params: { artistSlug: string[] }
    searchParams?: never
    prefetch?: boolean; scroll?: boolean; children?: import('react').ReactNode
  }): import('react').JSX.Element
  export function Link(props: Omit<import('react').AnchorHTMLAttributes<HTMLAnchorElement>, 'href'> & {
    href: '/[artistSlug]'
    params: { artistSlug: string | number }
    searchParams?: never
    prefetch?: boolean; scroll?: boolean; children?: import('react').ReactNode
  }): import('react').JSX.Element
  export function Link(props: Omit<import('react').AnchorHTMLAttributes<HTMLAnchorElement>, 'href'> & {
    href: '/[artistSlug]'
    params: { artistSlug: string | number }
    searchParams?: never
    prefetch?: boolean; scroll?: boolean; children?: import('react').ReactNode
  }): import('react').JSX.Element
  export function Link(props: Omit<import('react').AnchorHTMLAttributes<HTMLAnchorElement>, 'href'> & {
    href: '/[artistSlug]'
    params: { artistSlug: string | number }
    searchParams?: never
    prefetch?: boolean; scroll?: boolean; children?: import('react').ReactNode
  }): import('react').JSX.Element
  export function Link(props: Omit<import('react').AnchorHTMLAttributes<HTMLAnchorElement>, 'href'> & {
    href: '/[artistSlug]'
    params: { artistSlug: string | number }
    searchParams?: never
    prefetch?: boolean; scroll?: boolean; children?: import('react').ReactNode
  }): import('react').JSX.Element
  export function Link(props: Omit<import('react').AnchorHTMLAttributes<HTMLAnchorElement>, 'href'> & {
    href: '/[artistSlug]/[...year]'
    params: { artistSlug: string | number; year: string[] }
    searchParams?: never
    prefetch?: boolean; scroll?: boolean; children?: import('react').ReactNode
  }): import('react').JSX.Element
  export function Link(props: Omit<import('react').AnchorHTMLAttributes<HTMLAnchorElement>, 'href'> & {
    href: '/[artistSlug]/[year]'
    params: { artistSlug: string | number; year: string | number }
    searchParams?: never
    prefetch?: boolean; scroll?: boolean; children?: import('react').ReactNode
  }): import('react').JSX.Element
  export function Link(props: Omit<import('react').AnchorHTMLAttributes<HTMLAnchorElement>, 'href'> & {
    href: '/[artistSlug]/[year]'
    params: { artistSlug: string | number; year: string | number }
    searchParams?: never
    prefetch?: boolean; scroll?: boolean; children?: import('react').ReactNode
  }): import('react').JSX.Element
  export function Link(props: Omit<import('react').AnchorHTMLAttributes<HTMLAnchorElement>, 'href'> & {
    href: '/[artistSlug]/[year]'
    params: { artistSlug: string | number; year: string | number }
    searchParams?: never
    prefetch?: boolean; scroll?: boolean; children?: import('react').ReactNode
  }): import('react').JSX.Element
  export function Link(props: Omit<import('react').AnchorHTMLAttributes<HTMLAnchorElement>, 'href'> & {
    href: '/[artistSlug]/[year]/[month]'
    params: { artistSlug: string | number; year: string | number; month: string | number }
    searchParams?: never
    prefetch?: boolean; scroll?: boolean; children?: import('react').ReactNode
  }): import('react').JSX.Element
  export function Link(props: Omit<import('react').AnchorHTMLAttributes<HTMLAnchorElement>, 'href'> & {
    href: '/[artistSlug]/[year]/[month]/[...day]'
    params: { artistSlug: string | number; year: string | number; month: string | number; day: string[] }
    searchParams?: never
    prefetch?: boolean; scroll?: boolean; children?: import('react').ReactNode
  }): import('react').JSX.Element
  export function Link(props: Omit<import('react').AnchorHTMLAttributes<HTMLAnchorElement>, 'href'> & {
    href: '/[artistSlug]/[year]/[month]/[...day]'
    params: { artistSlug: string | number; year: string | number; month: string | number; day: string[] }
    searchParams?: never
    prefetch?: boolean; scroll?: boolean; children?: import('react').ReactNode
  }): import('react').JSX.Element
  export function Link(props: Omit<import('react').AnchorHTMLAttributes<HTMLAnchorElement>, 'href'> & {
    href: '/[artistSlug]/[year]/[month]/[day]'
    params: { artistSlug: string | number; year: string | number; month: string | number; day: string | number }
    searchParams?: never
    prefetch?: boolean; scroll?: boolean; children?: import('react').ReactNode
  }): import('react').JSX.Element
  export function Link(props: Omit<import('react').AnchorHTMLAttributes<HTMLAnchorElement>, 'href'> & {
    href: '/[artistSlug]/[year]/[month]/[day]/[songSlug]'
    params: { artistSlug: string | number; year: string | number; month: string | number; day: string | number; songSlug: string | number }
    searchParams?: never
    prefetch?: boolean; scroll?: boolean; children?: import('react').ReactNode
  }): import('react').JSX.Element
  export function Link(props: Omit<import('react').AnchorHTMLAttributes<HTMLAnchorElement>, 'href'> & {
    href: '/about'
    params?: never
    searchParams?: never
    prefetch?: boolean; scroll?: boolean; children?: import('react').ReactNode
  }): import('react').JSX.Element
  export function Link(props: Omit<import('react').AnchorHTMLAttributes<HTMLAnchorElement>, 'href'> & {
    href: '/app'
    params?: never
    searchParams?: never
    prefetch?: boolean; scroll?: boolean; children?: import('react').ReactNode
  }): import('react').JSX.Element
  export function Link(props: Omit<import('react').AnchorHTMLAttributes<HTMLAnchorElement>, 'href'> & {
    href: '/chat'
    params?: never
    searchParams?: never
    prefetch?: boolean; scroll?: boolean; children?: import('react').ReactNode
  }): import('react').JSX.Element
  export function Link(props: Omit<import('react').AnchorHTMLAttributes<HTMLAnchorElement>, 'href'> & {
    href: '/embed-test'
    params?: never
    searchParams?: never
    prefetch?: boolean; scroll?: boolean; children?: import('react').ReactNode
  }): import('react').JSX.Element
  export function Link(props: Omit<import('react').AnchorHTMLAttributes<HTMLAnchorElement>, 'href'> & {
    href: '/embed/[artistSlug]/[year]/[month]/[day]'
    params: { artistSlug: string | number; year: string | number; month: string | number; day: string | number }
    searchParams?: never
    prefetch?: boolean; scroll?: boolean; children?: import('react').ReactNode
  }): import('react').JSX.Element
  export function Link(props: Omit<import('react').AnchorHTMLAttributes<HTMLAnchorElement>, 'href'> & {
    href: '/embed/[artistSlug]/[year]/[month]/[day]/[songSlug]'
    params: { artistSlug: string | number; year: string | number; month: string | number; day: string | number; songSlug: string | number }
    searchParams?: never
    prefetch?: boolean; scroll?: boolean; children?: import('react').ReactNode
  }): import('react').JSX.Element
  export function Link(props: Omit<import('react').AnchorHTMLAttributes<HTMLAnchorElement>, 'href'> & {
    href: '/recently-played'
    params?: never
    searchParams?: never
    prefetch?: boolean; scroll?: boolean; children?: import('react').ReactNode
  }): import('react').JSX.Element
  export function Link(props: Omit<import('react').AnchorHTMLAttributes<HTMLAnchorElement>, 'href'> & {
    href: '/sonos'
    params?: never
    searchParams?: never
    prefetch?: boolean; scroll?: boolean; children?: import('react').ReactNode
  }): import('react').JSX.Element
  export function Link(props: Omit<import('react').AnchorHTMLAttributes<HTMLAnchorElement>, 'href'> & {
    href: '/today'
    params?: never
    searchParams?: never
    prefetch?: boolean; scroll?: boolean; children?: import('react').ReactNode
  }): import('react').JSX.Element
  export function Link(props: import('./client/link.js').LinkProps): import('react').JSX.Element
}
