# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build Status

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    environment: Production

    steps:
    - uses: actions/checkout@v4
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        buildkitd-config-inline: |
          [registry."100.97.22.118:32000"]
            http = true

    - name: Setup Tailscale
      uses: tailscale/github-action@v3
      with:
        oauth-client-id: ${{ secrets.TAILSCALE_OAUTH_CLIENT_ID }}
        oauth-secret: ${{ secrets.TAILSCALE_OAUTH_SECRET }}
        tags: tag:ci

    - name: Build Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: false
        load: true
        tags: |
          relisten2.tail09dbf.ts.net:32000/relistennet/relisten-web:latest
          100.97.22.118:32000/relistennet/relisten-web:latest

    - name: Push to registry using IP address
      run: |
        # Use the tailscale DNS name directly
        REGISTRY_ADDRESS="100.97.22.118"
        echo "Using registry: $REGISTRY_ADDRESS:32000"

        # Configure Docker to use this insecure registry
        echo '{
          "insecure-registries": ["'$REGISTRY_ADDRESS:32000'"]
        }' | sudo tee /etc/docker/daemon.json
        sudo systemctl restart docker
        sleep 5

        # Push the image (already properly tagged from the build step)
        docker push $REGISTRY_ADDRESS:32000/relistennet/relisten-web:latest

    - name: Install kubectl
      uses: azure/setup-kubectl@v3

    - name: Restart Kubernetes deployment
      run: |
        kubectl --server=https://100.97.22.118:6443 \
          --insecure-skip-tls-verify=true \
          --token=${{ secrets.KUBE_API_TOKEN }} \
          rollout restart deployment relisten-web
